<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-A92F397" failures="0" tests="1" name="sampletestng.InvocationTimeoutTest" time="0.068" errors="1" timestamp="22 Jan 2018 13:38:14 GMT" skipped="0">
  <testcase classname="sampletestng.InvocationTimeoutTest" name="countcheck" time="0.068">
    <error message="Method sampletestng.InvocationTimeoutTest.countcheck() didn&#039;t finish within the time-out 2" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method sampletestng.InvocationTimeoutTest.countcheck() didn't finish within the time-out 2at java.base@9.0.1/java.nio.ByteBuffer.flip(Unknown Source)at java.base@9.0.1/sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)at java.base@9.0.1/sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)at java.base@9.0.1/sun.nio.cs.StreamEncoder.flushBuffer(Unknown Source)at java.base@9.0.1/java.io.OutputStreamWriter.flushBuffer(Unknown Source)at java.base@9.0.1/java.io.PrintStream.newLine(Unknown Source)at java.base@9.0.1/java.io.PrintStream.println(Unknown Source)at app//sampletestng.InvocationTimeoutTest.countcheck(InvocationTimeoutTest.java:13)at java.base@9.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base@9.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at java.base@9.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.base@9.0.1/java.lang.reflect.Method.invoke(Unknown Source)at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:40)at java.base@9.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)at java.base@9.0.1/java.util.concurrent.FutureTask.run(Unknown Source)at java.base@9.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.base@9.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.base@9.0.1/java.lang.Thread.run(Unknown Source)]]>
    </error>
  </testcase> <!-- countcheck -->
</testsuite> <!-- sampletestng.InvocationTimeoutTest -->
